# This is a basic workflow to help you get started with Actions

name: Manual testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Pages deploy path
        id: get_root_url
        run: |
          echo $REPO
          echo ${REPO#courajs}
          echo hi
          echo "::set-output name=root_path::${REPO#${{github.repository_owner}}}/"
          echo "::set-output name=deploy_url::https://${{github.repository_owner}}.github.io/${REPO#${{github.repository_owner}}/}"
        env:
          REPO: ${{github.repository}}

      - name: Run
        run: |
          echo ${{steps.get_root_url.outputs.root_path}}
          echo ${{steps.get_root_url.outputs.deploy_url}}
      
      - name: Set repo URL
        run: >
          curl
          -X PATCH
          -H "Accept: application/vnd.github.v3+json"
          https://api.github.com/repos/${{github.repository}}
          -d '{"homepage":"${{steps.get_root_url.outputs.deploy_url}}"}'
