name: Update project name
on:
  create:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  update-project-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git status
      - run: grep -rl ember-auto-deploy .

