name: Update project name
on:
  push:
    branches: [ main, master ]
  create:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  update-project-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Pages deploy path
        id: get_root_url
        run: |
          echo "::set-output name=repo_name::${REPO#${{github.repository_owner}}/}"
        env:
          REPO: ${{github.repository}}
      - run: git status
      - run: ls -la
      - run: grep --version
      - run: grep --help
      - run: man grep
      - run: sed --help
      - run: man sed
      - run: grep -rl --exclude-dir=.git ember-testy .
      - run: >
          grep -rlZ
          --exclude-dir=.git
          --exclude-dir=.github
          ember-testy .
          | xargs -0 sed --in-place
          -e 's/ember-testy/${{steps.get_root_url.outputs.repo_name}}-new/g'
      - run: git status
      - run: git diff
      - run: git add -A; git commit; git push

